### ISSUE TITLE
.net 6.0 WebApi 中使用 PaddleOCRSharp  在docker中报错的问题

### ISSUE THREAD

**Issue by yudingjin** [raoyutian/PaddleOCRSharp#40]
System.DllNotFoundException: Unable to load shared library 'PaddleOCR.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libPaddleOCR.dll: cannot open shared object file: No such file or directory
         at PaddleOCRSharp.PaddleOCREngine.Initialize(String det_infer, String cls_infer, String rec_infer, String keys, OCRParameter parameter)
         at PaddleOCRSharp.PaddleOCREngine..ctor(OCRModelConfig config, OCRParameter parameter)

这个异常 如何解决

**Comment by raoyutian** [comment]
不支持linux.

**Comment by n0099** [comment]
https://github.com/sdcb/PaddleSharp
