### ISSUE TITLE
在ubuntu上运行报错，Unable to load shared library 'PaddleOCR'

### ISSUE THREAD

**Issue by BlueMain** [raoyutian/PaddleOCRSharp#56]
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'PaddleOCR' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libPaddleOCR: cannot open shared object file: No such file or directory
   at PaddleOCRSharp.PaddleOCREngine.Initialize(String det_infer, String cls_infer, String rec_infer, String keys, OCRParameter parameter)
   at PaddleOCRSharp.PaddleOCREngine..ctor(OCRModelConfig config, OCRParameter parameter)

这个是没有发布linux版的DLL吧 ?

**Comment by raoyutian** [comment]
付费的。
